### PR TITLE
Kotlin examples

### PR DESCRIPTION
**Pull request by binkley**
I decided against and example for "transactions".  Best I could tell (please correct if I'm wrong!), this is simply using a Map as the data for the block.  This is natural and easy in Kotlin.

### CODE REVIEW

**Comment by geraldb** [comment]
@binkley   Thanks  for (sharing) the great Kotlin examples. If I get around I will add your credits (your name), of course to the page.   Keep it up. If you want to add or change something, always welcome. Cheers. Prosit 2020!

**Comment by geraldb** [comment]
@binkley FYI: I've (finally) added your byline and credits (and removed the duplicate questions and comments section) from the README page. Thanks again. Cheers. Prosit 2020!

**Comment by binkley** [comment]
FYI -- I have a request from a CS prof friend to reimplement with a Merkel tree rather than list.  That would defeat the point of a simple example!

**Comment by geraldb** [comment]
You can find a simple calculate the merkle tree hash in ruby in this repo too, see <https://github.com/openblockchains/awesome-blockchains/tree/master/merkletree.rb>  as stated it was inspired, that is, converted really over from the C++ example from the Bitcoin Programming book.  You're of course welcome to add a merkle tree example in Kotlin or write an article and than add the link to the Build Your Own __ with Kotlin section to the awesome page here. Cheers. Prost.

**Pull request merged**
